// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently
//

//#pragma once

//#include "targetver.h"

// TODO: reference additional headers your program requires here
#include "system/console.h"
#include "system/enum.h"
#include "system/shared_ptr.h"
#include "system/string.h"
#include "system/io/file.h"
#include "system/io/memory_stream.h"
#include "system/io/stream_reader.h"
#include "system/io/seekorigin.h"
#include "system/text/unicode_encoding.h"
#include "drawing/rectangle.h"
#include "drawing/bitmap.h"
#include "drawing/graphics.h"

#include "Aspose.PDF.Cpp/Color.h"
#include "Aspose.PDF.Cpp/Data/XMP/XmpValue.h"
#include "Aspose.PDF.Cpp/Direction.h"
#include "Aspose.PDF.Cpp/DOM/PageMode_.h"
#include "Aspose.PDF.Cpp/Document.h"
#include "Aspose.PDF.Cpp/DocumentInfo.h"
#include "Aspose.PDF.Cpp/EmbeddedFileCollection.h"
#include "Aspose.PDF.Cpp/License.h"
#include "Aspose.PDF.Cpp/Metadata.h"
#include "Aspose.PDF.Cpp/Page_.h"
#include "Aspose.PDF.Cpp/PageCollection.h"
#include "Aspose.PDF.Cpp/PageLayout.h"
#include "Aspose.PDF.Cpp/Rectangle_.h"
#include "Aspose.PDF.Cpp/Facades/PdfFileInfo.h"
#include "Aspose.PDF.Cpp/Facades/PdfContentEditor.h"
#include "Aspose.PDF.Cpp/Facades/PdfExtractor.h"
#include "Aspose.PDF.Cpp/Generator/PageInfo.h"
#include "Aspose.PDF.Cpp/Generator/Paragraphs.h"
#include "Aspose.PDF.Cpp/HorizontalAlignment.h"
#include "Aspose.PDF.Cpp/VerticalAlignment.h"
#include "Aspose.PDF.Cpp/InteractiveFeatures/GoToAction.h"
#include "Aspose.PDF.Cpp/InteractiveFeatures/FitExplicitDestination.h"
#include "Aspose.PDF.Cpp/InteractiveFeatures/XYZExplicitDestination.h"
#include "Aspose.PDF.Cpp/Text/Font.h"
#include "Aspose.PDF.Cpp/Text/FontStyles.h"
#include "Aspose.PDF.Cpp/Text/FontRepository.h"
#include "Aspose.PDF.Cpp/Text/Position.h"
#include "Aspose.PDF.Cpp/Text/TextBuilder.h"
#include "Aspose.PDF.Cpp/Text/TextFragment.h"
#include "Aspose.PDF.Cpp/Text/TextFragmentCollection.h"
#include "Aspose.PDF.Cpp/Text/TextFragmentAbsorber.h"
#include "Aspose.PDF.Cpp/Text/TextFragmentState.h"
#include "Aspose.PDF.Cpp/Text/TextParagraph.h"
#include "Aspose.PDF.Cpp/Text/TextOptions/TextReplaceOptions.h"
#include "Aspose.PDF.Cpp/IO/ConvertStrategies/PdfFormat.h"
#include "Aspose.PDF.Cpp/IO/ConvertStrategies/ConvertErrorAction.h"
#include "Aspose.PDF.Cpp/Facades/DocumentPrivilege.h"
#include "Aspose.PDF.Cpp/Facades/PdfBookmarkEditor.h"
#include "Aspose.PDF.Cpp/Facades/Bookmark.h"
#include "Aspose.PDF.Cpp/Facades/Bookmarks.h"
#include "Aspose.PDF.Cpp/Facades/PdfAnnotationEditor.h"
#include "Aspose.PDF.Cpp/InteractiveFeatures/Annotations/TextAnnotation.h"
#include "Aspose.PDF.Cpp/InteractiveFeatures/Annotations/AnnotationType.h"
#include "Aspose.PDF.Cpp/Facades/PdfConverter.h"
#include "Aspose.PDF.Cpp/DocSaveOptions.h"
#include "Aspose.PDF.Cpp/SvgSaveOptions.h"
#include "Aspose.PDF.Cpp/Table/Table.h"
#include "Aspose.PDF.Cpp/Table/Row.h"
#include "Aspose.PDF.Cpp/Table/Rows.h"
#include "Aspose.PDF.Cpp/Table/Cell.h"
#include "Aspose.PDF.Cpp/Table/Cells.h"
#include "Aspose.PDF.Cpp/Generator/Paragraphs.h"
#include "Aspose.PDF.Cpp/Generator/BorderInfo.h"
#include "Aspose.PDF.Cpp/Generator/BorderSide.h"