#ifndef _brushes_h_
#define _brushes_h_

#include "fwd.h"
#include "drawing/brush.h"

namespace System { namespace Drawing {

    class Brushes
    {
    public:
        static SharedPtr<Brush> get_AliceBlue();
        static SharedPtr<Brush> get_AntiqueWhite();
        static SharedPtr<Brush> get_Aqua();
        static SharedPtr<Brush> get_Aquamarine();
        static SharedPtr<Brush> get_Azure();
        static SharedPtr<Brush> get_Beige();
        static SharedPtr<Brush> get_Bisque();
        static SharedPtr<Brush> get_Black();
        static SharedPtr<Brush> get_BlanchedAlmond();
        static SharedPtr<Brush> get_Blue();
        static SharedPtr<Brush> get_BlueViolet();
        static SharedPtr<Brush> get_Brown();
        static SharedPtr<Brush> get_BurlyWood();
        static SharedPtr<Brush> get_CadetBlue();
        static SharedPtr<Brush> get_Chartreuse();
        static SharedPtr<Brush> get_Chocolate();
        static SharedPtr<Brush> get_Coral();
        static SharedPtr<Brush> get_CornflowerBlue();
        static SharedPtr<Brush> get_Cornsilk();
        static SharedPtr<Brush> get_Crimson();
        static SharedPtr<Brush> get_Cyan();
        static SharedPtr<Brush> get_DarkBlue();
        static SharedPtr<Brush> get_DarkCyan();
        static SharedPtr<Brush> get_DarkGoldenrod();
        static SharedPtr<Brush> get_DarkGray();
        static SharedPtr<Brush> get_DarkGreen();
        static SharedPtr<Brush> get_DarkKhaki();
        static SharedPtr<Brush> get_DarkMagenta();
        static SharedPtr<Brush> get_DarkOliveGreen();
        static SharedPtr<Brush> get_DarkOrange();
        static SharedPtr<Brush> get_DarkOrchid();
        static SharedPtr<Brush> get_DarkRed();
        static SharedPtr<Brush> get_DarkSalmon();
        static SharedPtr<Brush> get_DarkSeaGreen();
        static SharedPtr<Brush> get_DarkSlateBlue();
        static SharedPtr<Brush> get_DarkSlateGray();
        static SharedPtr<Brush> get_DarkTurquoise();
        static SharedPtr<Brush> get_DarkViolet();
        static SharedPtr<Brush> get_DeepPink();
        static SharedPtr<Brush> get_DeepSkyBlue();
        static SharedPtr<Brush> get_DimGray();
        static SharedPtr<Brush> get_DodgerBlue();
        static SharedPtr<Brush> get_Firebrick();
        static SharedPtr<Brush> get_FloralWhite();
        static SharedPtr<Brush> get_ForestGreen();
        static SharedPtr<Brush> get_Fuchsia();
        static SharedPtr<Brush> get_Gainsboro();
        static SharedPtr<Brush> get_GhostWhite();
        static SharedPtr<Brush> get_Gold();
        static SharedPtr<Brush> get_Goldenrod();
        static SharedPtr<Brush> get_Gray();
        static SharedPtr<Brush> get_Green();
        static SharedPtr<Brush> get_GreenYellow();
        static SharedPtr<Brush> get_Honeydew();
        static SharedPtr<Brush> get_HotPink();
        static SharedPtr<Brush> get_IndianRed();
        static SharedPtr<Brush> get_Indigo();
        static SharedPtr<Brush> get_Ivory();
        static SharedPtr<Brush> get_Khaki();
        static SharedPtr<Brush> get_Lavender();
        static SharedPtr<Brush> get_LavenderBlush();
        static SharedPtr<Brush> get_LawnGreen();
        static SharedPtr<Brush> get_LemonChiffon();
        static SharedPtr<Brush> get_LightBlue();
        static SharedPtr<Brush> get_LightCoral();
        static SharedPtr<Brush> get_LightCyan();
        static SharedPtr<Brush> get_LightGoldenrodYellow();
        static SharedPtr<Brush> get_LightGray();
        static SharedPtr<Brush> get_LightGreen();
        static SharedPtr<Brush> get_LightPink();
        static SharedPtr<Brush> get_LightSalmon();
        static SharedPtr<Brush> get_LightSeaGreen();
        static SharedPtr<Brush> get_LightSkyBlue();
        static SharedPtr<Brush> get_LightSlateGray();
        static SharedPtr<Brush> get_LightSteelBlue();
        static SharedPtr<Brush> get_LightYellow();
        static SharedPtr<Brush> get_Lime();
        static SharedPtr<Brush> get_LimeGreen();
        static SharedPtr<Brush> get_Linen();
        static SharedPtr<Brush> get_Magenta();
        static SharedPtr<Brush> get_Maroon();
        static SharedPtr<Brush> get_MediumAquamarine();
        static SharedPtr<Brush> get_MediumBlue();
        static SharedPtr<Brush> get_MediumOrchid();
        static SharedPtr<Brush> get_MediumPurple();
        static SharedPtr<Brush> get_MediumSeaGreen();
        static SharedPtr<Brush> get_MediumSlateBlue();
        static SharedPtr<Brush> get_MediumSpringGreen();
        static SharedPtr<Brush> get_MediumTurquoise();
        static SharedPtr<Brush> get_MediumVioletRed();
        static SharedPtr<Brush> get_MidnightBlue();
        static SharedPtr<Brush> get_MintCream();
        static SharedPtr<Brush> get_MistyRose();
        static SharedPtr<Brush> get_Moccasin();
        static SharedPtr<Brush> get_NavajoWhite();
        static SharedPtr<Brush> get_Navy();
        static SharedPtr<Brush> get_OldLace();
        static SharedPtr<Brush> get_Olive();
        static SharedPtr<Brush> get_OliveDrab();
        static SharedPtr<Brush> get_Orange();
        static SharedPtr<Brush> get_OrangeRed();
        static SharedPtr<Brush> get_Orchid();
        static SharedPtr<Brush> get_PaleGoldenrod();
        static SharedPtr<Brush> get_PaleGreen();
        static SharedPtr<Brush> get_PaleTurquoise();
        static SharedPtr<Brush> get_PaleVioletRed();
        static SharedPtr<Brush> get_PapayaWhip();
        static SharedPtr<Brush> get_PeachPuff();
        static SharedPtr<Brush> get_Peru();
        static SharedPtr<Brush> get_Pink();
        static SharedPtr<Brush> get_Plum();
        static SharedPtr<Brush> get_PowderBlue();
        static SharedPtr<Brush> get_Purple();
        static SharedPtr<Brush> get_Red();
        static SharedPtr<Brush> get_RosyBrown();
        static SharedPtr<Brush> get_RoyalBlue();
        static SharedPtr<Brush> get_SaddleBrown();
        static SharedPtr<Brush> get_Salmon();
        static SharedPtr<Brush> get_SandyBrown();
        static SharedPtr<Brush> get_SeaGreen();
        static SharedPtr<Brush> get_SeaShell();
        static SharedPtr<Brush> get_Sienna();
        static SharedPtr<Brush> get_Silver();
        static SharedPtr<Brush> get_SkyBlue();
        static SharedPtr<Brush> get_SlateBlue();
        static SharedPtr<Brush> get_SlateGray();
        static SharedPtr<Brush> get_Snow();
        static SharedPtr<Brush> get_SpringGreen();
        static SharedPtr<Brush> get_SteelBlue();
        static SharedPtr<Brush> get_Tan();
        static SharedPtr<Brush> get_Teal();
        static SharedPtr<Brush> get_Thistle();
        static SharedPtr<Brush> get_Tomato();
        static SharedPtr<Brush> get_Transparent();
        static SharedPtr<Brush> get_Turquoise();
        static SharedPtr<Brush> get_Violet();
        static SharedPtr<Brush> get_Wheat();
        static SharedPtr<Brush> get_White();
        static SharedPtr<Brush> get_WhiteSmoke();
        static SharedPtr<Brush> get_Yellow();
        static SharedPtr<Brush> get_YellowGreen();

    private:
        static const SharedPtr<Brush> m_AliceBlue;
        static const SharedPtr<Brush> m_AntiqueWhite;
        static const SharedPtr<Brush> m_Aqua;
        static const SharedPtr<Brush> m_Aquamarine;
        static const SharedPtr<Brush> m_Azure;
        static const SharedPtr<Brush> m_Beige;
        static const SharedPtr<Brush> m_Bisque;
        static const SharedPtr<Brush> m_Black;
        static const SharedPtr<Brush> m_BlanchedAlmond;
        static const SharedPtr<Brush> m_Blue;
        static const SharedPtr<Brush> m_BlueViolet;
        static const SharedPtr<Brush> m_Brown;
        static const SharedPtr<Brush> m_BurlyWood;
        static const SharedPtr<Brush> m_CadetBlue;
        static const SharedPtr<Brush> m_Chartreuse;
        static const SharedPtr<Brush> m_Chocolate;
        static const SharedPtr<Brush> m_Coral;
        static const SharedPtr<Brush> m_CornflowerBlue;
        static const SharedPtr<Brush> m_Cornsilk;
        static const SharedPtr<Brush> m_Crimson;
        static const SharedPtr<Brush> m_Cyan;
        static const SharedPtr<Brush> m_DarkBlue;
        static const SharedPtr<Brush> m_DarkCyan;
        static const SharedPtr<Brush> m_DarkGoldenrod;
        static const SharedPtr<Brush> m_DarkGray;
        static const SharedPtr<Brush> m_DarkGreen;
        static const SharedPtr<Brush> m_DarkKhaki;
        static const SharedPtr<Brush> m_DarkMagenta;
        static const SharedPtr<Brush> m_DarkOliveGreen;
        static const SharedPtr<Brush> m_DarkOrange;
        static const SharedPtr<Brush> m_DarkOrchid;
        static const SharedPtr<Brush> m_DarkRed;
        static const SharedPtr<Brush> m_DarkSalmon;
        static const SharedPtr<Brush> m_DarkSeaGreen;
        static const SharedPtr<Brush> m_DarkSlateBlue;
        static const SharedPtr<Brush> m_DarkSlateGray;
        static const SharedPtr<Brush> m_DarkTurquoise;
        static const SharedPtr<Brush> m_DarkViolet;
        static const SharedPtr<Brush> m_DeepPink;
        static const SharedPtr<Brush> m_DeepSkyBlue;
        static const SharedPtr<Brush> m_DimGray;
        static const SharedPtr<Brush> m_DodgerBlue;
        static const SharedPtr<Brush> m_Firebrick;
        static const SharedPtr<Brush> m_FloralWhite;
        static const SharedPtr<Brush> m_ForestGreen;
        static const SharedPtr<Brush> m_Fuchsia;
        static const SharedPtr<Brush> m_Gainsboro;
        static const SharedPtr<Brush> m_GhostWhite;
        static const SharedPtr<Brush> m_Gold;
        static const SharedPtr<Brush> m_Goldenrod;
        static const SharedPtr<Brush> m_Gray;
        static const SharedPtr<Brush> m_Green;
        static const SharedPtr<Brush> m_GreenYellow;
        static const SharedPtr<Brush> m_Honeydew;
        static const SharedPtr<Brush> m_HotPink;
        static const SharedPtr<Brush> m_IndianRed;
        static const SharedPtr<Brush> m_Indigo;
        static const SharedPtr<Brush> m_Ivory;
        static const SharedPtr<Brush> m_Khaki;
        static const SharedPtr<Brush> m_Lavender;
        static const SharedPtr<Brush> m_LavenderBlush;
        static const SharedPtr<Brush> m_LawnGreen;
        static const SharedPtr<Brush> m_LemonChiffon;
        static const SharedPtr<Brush> m_LightBlue;
        static const SharedPtr<Brush> m_LightCoral;
        static const SharedPtr<Brush> m_LightCyan;
        static const SharedPtr<Brush> m_LightGoldenrodYellow;
        static const SharedPtr<Brush> m_LightGray;
        static const SharedPtr<Brush> m_LightGreen;
        static const SharedPtr<Brush> m_LightPink;
        static const SharedPtr<Brush> m_LightSalmon;
        static const SharedPtr<Brush> m_LightSeaGreen;
        static const SharedPtr<Brush> m_LightSkyBlue;
        static const SharedPtr<Brush> m_LightSlateGray;
        static const SharedPtr<Brush> m_LightSteelBlue;
        static const SharedPtr<Brush> m_LightYellow;
        static const SharedPtr<Brush> m_Lime;
        static const SharedPtr<Brush> m_LimeGreen;
        static const SharedPtr<Brush> m_Linen;
        static const SharedPtr<Brush> m_Magenta;
        static const SharedPtr<Brush> m_Maroon;
        static const SharedPtr<Brush> m_MediumAquamarine;
        static const SharedPtr<Brush> m_MediumBlue;
        static const SharedPtr<Brush> m_MediumOrchid;
        static const SharedPtr<Brush> m_MediumPurple;
        static const SharedPtr<Brush> m_MediumSeaGreen;
        static const SharedPtr<Brush> m_MediumSlateBlue;
        static const SharedPtr<Brush> m_MediumSpringGreen;
        static const SharedPtr<Brush> m_MediumTurquoise;
        static const SharedPtr<Brush> m_MediumVioletRed;
        static const SharedPtr<Brush> m_MidnightBlue;
        static const SharedPtr<Brush> m_MintCream;
        static const SharedPtr<Brush> m_MistyRose;
        static const SharedPtr<Brush> m_Moccasin;
        static const SharedPtr<Brush> m_NavajoWhite;
        static const SharedPtr<Brush> m_Navy;
        static const SharedPtr<Brush> m_OldLace;
        static const SharedPtr<Brush> m_Olive;
        static const SharedPtr<Brush> m_OliveDrab;
        static const SharedPtr<Brush> m_Orange;
        static const SharedPtr<Brush> m_OrangeRed;
        static const SharedPtr<Brush> m_Orchid;
        static const SharedPtr<Brush> m_PaleGoldenrod;
        static const SharedPtr<Brush> m_PaleGreen;
        static const SharedPtr<Brush> m_PaleTurquoise;
        static const SharedPtr<Brush> m_PaleVioletRed;
        static const SharedPtr<Brush> m_PapayaWhip;
        static const SharedPtr<Brush> m_PeachPuff;
        static const SharedPtr<Brush> m_Peru;
        static const SharedPtr<Brush> m_Pink;
        static const SharedPtr<Brush> m_Plum;
        static const SharedPtr<Brush> m_PowderBlue;
        static const SharedPtr<Brush> m_Purple;
        static const SharedPtr<Brush> m_Red;
        static const SharedPtr<Brush> m_RosyBrown;
        static const SharedPtr<Brush> m_RoyalBlue;
        static const SharedPtr<Brush> m_SaddleBrown;
        static const SharedPtr<Brush> m_Salmon;
        static const SharedPtr<Brush> m_SandyBrown;
        static const SharedPtr<Brush> m_SeaGreen;
        static const SharedPtr<Brush> m_SeaShell;
        static const SharedPtr<Brush> m_Sienna;
        static const SharedPtr<Brush> m_Silver;
        static const SharedPtr<Brush> m_SkyBlue;
        static const SharedPtr<Brush> m_SlateBlue;
        static const SharedPtr<Brush> m_SlateGray;
        static const SharedPtr<Brush> m_Snow;
        static const SharedPtr<Brush> m_SpringGreen;
        static const SharedPtr<Brush> m_SteelBlue;
        static const SharedPtr<Brush> m_Tan;
        static const SharedPtr<Brush> m_Teal;
        static const SharedPtr<Brush> m_Thistle;
        static const SharedPtr<Brush> m_Tomato;
        static const SharedPtr<Brush> m_Transparent;
        static const SharedPtr<Brush> m_Turquoise;
        static const SharedPtr<Brush> m_Violet;
        static const SharedPtr<Brush> m_Wheat;
        static const SharedPtr<Brush> m_White;
        static const SharedPtr<Brush> m_WhiteSmoke;
        static const SharedPtr<Brush> m_Yellow;
        static const SharedPtr<Brush> m_YellowGreen;
    };

}}


#endif